#pragma once

#include "types.h"
#include "helpers/Constants.hpp"
#include "helpers/math.hpp"
#include "level/level_cmds.h"

const static int levelStream[] = {
	cmd_newChapter(0),
	cmd_useBackground(LUTs::BgImageId::STAGE1_0, 0, 0, 0, 0, LUTs::BgTravelingId::bgHandle_default),
	cmd_useBackground(LUTs::BgImageId::STAGE1_1, 0, 0, 128, itofix(1), LUTs::BgTravelingId::bgHandle_default),
	cmd_useBackground(LUTs::BgImageId::STAGE1_2, 0, 0, itofix(1), itofix(1), LUTs::BgTravelingId::bgHandle_default),
	cmd_useBackground(LUTs::BgImageId::STAGE1_3, 0, 0, itofix(1) + 128, itofix(1), LUTs::BgTravelingId::bgHandle_default),
	cmd_useBackground(LUTs::BgImageId::STAGE1_4, 0, 0, itofix(2), itofix(1), LUTs::BgTravelingId::bgHandle_default),
	cmd_playMusic(LUTs::MusicId::CHAPTER1_MAIN, LUTs::MusicId::CHAPTER1_LOOP),
	cmd_newCameraPath(LUTs::CamTravelingId::CameraPath_i1),
	cmd_wait(64),
	//
	// Introduction 1
	//
	// Wave 1
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_1, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_1, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_1, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_1, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_1, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_1, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(64),
	cmd_newWave,
	// Wave 2
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_2, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_2, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_2, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_2, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_2, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_2, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(32),
	cmd_newWave,
	// Wave 3
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_3, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_3, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_3, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_3, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_3, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_3, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_4, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_4, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_4, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_4, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_4, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(16),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_4, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	// cmd_killed,
	cmd_wait(100),
	//cmd_newWave,
	// Wave 4
	enemy(85, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(115, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(145, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(175, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(205, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(235, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(85, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(115, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(145, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(175, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(205, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(235, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(85, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(115, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(145, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(175, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(205, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(235, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(85, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(115, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(145, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(175, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(205, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(235, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(85, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(115, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(145, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(175, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(205, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(235, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(85, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(115, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(145, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_5, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(175, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(205, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(235, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_5, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(20),
	// cmd_killed,
	cmd_wait(100),
	cmd_killed,
	cmd_skipAbs(17 * Constants::FPS, 12),
	cmd_newWave,
	// Wave 5
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_1, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_1, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_1, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(64),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_2, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_2, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_2, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	//cmd_killed,
	cmd_waitAbs(21 * Constants::FPS), // aim at 21 seconds
	cmd_newWave,
	cmd_startChapter(),
	cmd_newCameraPath(LUTs::CamTravelingId::CameraPath_c1),
	//
	// Chapter 1
	//
	// Wave 1
	cmd_wait(128),
	enemy(53, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	enemy(106, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	enemy(79, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(128),
	enemy(214, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	enemy(267, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	enemy(240, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(128),
	enemy(214, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(267, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(240, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	cmd_wait(128),
	enemy(53, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(106, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(79, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	enemy(53, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	enemy(106, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	enemy(79, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_7, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(214, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(267, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(240, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_7, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	// Wave 2
	enemy(53, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_8, Constants::LIGHT, 1, 8, TYPE_ENEMY),
	enemy(106, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_8, Constants::LIGHT, 1, 8, TYPE_ENEMY),
	enemy(79, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_8, Constants::LIGHT, 1, 8, TYPE_ENEMY),
	cmd_wait(128),
	enemy(214, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_8, Constants::SHADOW, 1, 8, TYPE_ENEMY),
	enemy(267, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_8, Constants::SHADOW, 1, 8, TYPE_ENEMY),	
	enemy(240, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_8, Constants::SHADOW, 1, 8, TYPE_ENEMY),
	cmd_wait(256),
	// Wave 3
	enemy(45, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_8, Constants::SHADOW, 1, 8, TYPE_ENEMY),
	enemy(90, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_8, Constants::SHADOW, 1, 8, TYPE_ENEMY),
	enemy(135, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_8, Constants::LIGHT, 1, 8, TYPE_ENEMY),
	enemy(185, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_8, Constants::SHADOW, 1, 8, TYPE_ENEMY),
	enemy(230, -35, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_8, Constants::LIGHT, 1, 8, TYPE_ENEMY),	
	enemy(275, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_8, Constants::LIGHT, 1, 8, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	// Wave 4
	enemy(320, 0, 6, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_9, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 6, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_9, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(320, 0, 6, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_9, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(48),
	enemy(160, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_10, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(160, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_10, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(160, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_10, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(160, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_10, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(160, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_10, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(160, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_10, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(50, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_11, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(270, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_11, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(50, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_11, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(270, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_11, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	cmd_wait(32),
	enemy(50, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_11, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(270, 0, 10, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_11, Constants::SHADOW, 0, 8, TYPE_ENEMY),	
	cmd_killed,
	cmd_newWave,
	// Wave 5
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_1, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_1, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_1, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(128),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_2, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_2, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(32),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_2, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_killed,
	cmd_wait(64),
	cmd_newWave,
	// Wave 6
	enemy(100, -80, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(140, -80, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(180, -80, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(220, -80, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(20, -40, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(60, -40, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(100, -50, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(140, -50, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(180, -50, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(220, -50, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(260, -40, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(300, -40, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(20, -10, 0, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(60, -10, 0, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(100, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(140, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(180, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(220, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(260, -10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(300, -10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(100, 10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(140, 10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(180, 10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_12, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(220, 10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_12, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_killed,
	cmd_wait(64),
	cmd_newWave,
	// Wave 7
	enemy(106, 0, 100, LUTs::BaseImageId::ENEMY_SHIP_3_SHADOW, LUTs::EnemyPatternId::Pattern_1_13, Constants::SHADOW, 1, 30, TYPE_ENEMY),
	enemy(212, 0, 100, LUTs::BaseImageId::ENEMY_SHIP_3_LIGHT, LUTs::EnemyPatternId::Pattern_1_14, Constants::LIGHT, 1, 30, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_15, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_15, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_joint(2, 0, 0, 0, 0),
	cmd_joint(3, 0, 0, 0, 0),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_15, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_15, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_joint(4, 1, 0, 0, 0),
	cmd_joint(5, 1, 0, 0, 0),
	cmd_killed,
	cmd_wait(64),
	cmd_newWave,
	// Wave 8
	enemy(120, 0, 6, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_16, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(160, 0, 6, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_16, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(200, 0, 6, LUTs::BaseImageId::ENEMY_SHIP_2_SHADOW, LUTs::EnemyPatternId::Pattern_1_16, Constants::SHADOW, 0, 8, TYPE_ENEMY),
	enemy(140, -50, 6, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_16, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	enemy(180, -50, 6, LUTs::BaseImageId::ENEMY_SHIP_2_LIGHT, LUTs::EnemyPatternId::Pattern_1_16, Constants::LIGHT, 0, 8, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	// Wave 9
	enemy(160, -50, 100, LUTs::BaseImageId::ENEMY_SHIP_3_LIGHT, LUTs::EnemyPatternId::Pattern_1_17, Constants::LIGHT, 1, 40, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	// Wave 10
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_18, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_18, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_18, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_18, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_18, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_18, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_18, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_18, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_1_18, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_18, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_18, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_1_18, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	// Wave 11
	enemy(340, 55, 120, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHT, LUTs::EnemyPatternId::Pattern_1_19, Constants::LIGHT, 0, 40, TYPE_ENEMY),
	enemy(-20, 170, 120, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOW, LUTs::EnemyPatternId::Pattern_1_19, Constants::SHADOW, 0, 40, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHTBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::LIGHT, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHTBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::LIGHT, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHTBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::LIGHT, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHTBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::LIGHT, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHTBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::LIGHT, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHTBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::LIGHT, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHTBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::LIGHT, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_LIGHTBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::LIGHT, 0, 10, TYPE_ENEMY),
	cmd_joint(2, 0, -22, -3, 1),
	cmd_joint(3, 0, 22, -3, 1),
	cmd_joint(4, 0, -22, 10, 1),
	cmd_joint(5, 0, 22, 10, 1),
	cmd_joint(6, 0, -22, 31, 1),
	cmd_joint(7, 0, 22, 31, 1),
	cmd_joint(8, 0, -22, 45, 1),
	cmd_joint(9, 0, 22, 45, 1),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOWBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::SHADOW, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOWBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::SHADOW, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOWBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::SHADOW, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOWBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::SHADOW, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOWBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::SHADOW, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOWBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::SHADOW, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOWBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::SHADOW, 0, 10, TYPE_ENEMY),
	enemy(0, 0, 2, LUTs::BaseImageId::ENEMY_SHIP_4_SHADOWBALL, LUTs::EnemyPatternId::Pattern_1_20, Constants::SHADOW, 0, 10, TYPE_ENEMY),
	cmd_joint(10, 1, -22, -3, 1),
	cmd_joint(11, 1, 22, -3, 1),
	cmd_joint(12, 1, -22, 10, 1),
	cmd_joint(13, 1, 22, 10, 1),
	cmd_joint(14, 1, -22, 31, 1),
	cmd_joint(15, 1, 22, 31, 1),
	cmd_joint(16, 1, -22, 45, 1),
	cmd_joint(17, 1, 22, 45, 1),
	cmd_wait(1024),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_SHADOW, LUTs::EnemyPatternId::Pattern_1_21, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(96),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(160, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_1_LIGHT, LUTs::EnemyPatternId::Pattern_1_21, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	cmd_wait(128),
	// Boss
	cmd_fightBoss(0),
	LVLSTR_CHAPTEREND,
	//*/
	cmd_newChapter(1),
	/******************
	 * Introduction 2 *
	 ******************/
	cmd_useBackground(LUTs::BgImageId::STAGE2_0, 0, 0, itofix(1), itofix(1), LUTs::BgTravelingId::bgHandle_default),
	cmd_useBackground(LUTs::BgImageId::STAGE2_1, 0, 0, itofix(2), itofix(1), LUTs::BgTravelingId::bgHandle_default),
	cmd_playMusic(LUTs::MusicId::CHAPTER2_MAIN, LUTs::MusicId::CHAPTER2_LOOP),
	cmd_newCameraPath(LUTs::CamTravelingId::CameraPath_i2),
	// Wave 1
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(340, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_1, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_wait(16),
	enemy(-20, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_1, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	// Wave 2
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_2, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_3, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	cmd_wait(40),
	enemy(40, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(340, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_wait(20),
	enemy(280, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_2, Constants::LIGHT, 1, 2, TYPE_ENEMY),
	enemy(-20, 40, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_3, Constants::SHADOW, 1, 2, TYPE_ENEMY),
	cmd_repeatAbs(22 * Constants::FPS, 6),
	cmd_waitAbs(27 * Constants::FPS),
	cmd_newWave,
	// Wave 3
	enemy(-40, 30, 20, LUTs::BaseImageId::ENEMY_SHIP_6_LIGHT, LUTs::EnemyPatternId::Pattern_2_4, Constants::LIGHT, 0, 20, TYPE_ENEMY),
	enemy(360, 30, 20, LUTs::BaseImageId::ENEMY_SHIP_6_LIGHT, LUTs::EnemyPatternId::Pattern_2_4, Constants::LIGHT, 0, 20, TYPE_ENEMY),
	cmd_wait(100),
	enemy(-10, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_5, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(-30, 75, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_5, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(-10, 90, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_5, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(-30, 105, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_5, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(-10, 120, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_5, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(-30, 135, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_5, Constants::SHADOW, 1, 5, TYPE_ENEMY),
	enemy(330, 60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_5, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(350, 75, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_5, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(330, 90, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_5, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(350, 105, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_5, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(330, 120, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_5, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(350, 135, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_5, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	enemy(160, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_6, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(15),
	enemy(160, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_6, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(15),
	enemy(160, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_6, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(15),
	enemy(160, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_6, Constants::LIGHT, 1, 5, TYPE_ENEMY),
	cmd_wait(192),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(15),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(15),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(15),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(15),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(15),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_SHADOW, LUTs::EnemyPatternId::Pattern_2_7, Constants::SHADOW, 0, 2, TYPE_ENEMY),
	cmd_wait(15),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(15),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(15),
	enemy(135, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(185, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_wait(64),
	enemy(80, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(65, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(95, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(240, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(225, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	enemy(255, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_5_LIGHT, LUTs::EnemyPatternId::Pattern_2_7, Constants::LIGHT, 0, 2, TYPE_ENEMY),
	cmd_waitAbs(39 * Constants::FPS + Constants::FPS / 2),
	//*/
	cmd_startChapter(),
	cmd_resetBackgrounds,
	cmd_useBackground(LUTs::BgImageId::STAGE2_2, 0, 120, 128, itofix(1), LUTs::BgTravelingId::bgHandle_default),
	cmd_useBackground(LUTs::BgImageId::STAGE2_3, 0, 120, 160, itofix(1), LUTs::BgTravelingId::bgHandle_default),
	cmd_useBackground(LUTs::BgImageId::STAGE2_4, 0, 120, 182, itofix(1), LUTs::BgTravelingId::bgHandle_2_2),
	cmd_useBackground(LUTs::BgImageId::STAGE2_5, 0, 120, 187, itofix(1), LUTs::BgTravelingId::bgHandle_2_2),
	cmd_useBackground(LUTs::BgImageId::STAGE2_6, 0, 120, 192, itofix(1), LUTs::BgTravelingId::bgHandle_2_2),
	cmd_useBackground(LUTs::BgImageId::STAGE2_7, 0, 120, 200, itofix(1), LUTs::BgTravelingId::bgHandle_2_2),
	cmd_wait(2 * Constants::FPS),
	cmd_newCameraPath(LUTs::CamTravelingId::CameraPath_c2),
	cmd_newWave,
	//
	// Chapter 2
	//
	// Wave 1
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_8, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_8, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_8, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_8, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_8, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_8, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_8, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_8, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_8, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_8, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_8, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_8, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_9, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_9, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_9, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_9, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_9, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_9, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_9, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_9, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_9, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_9, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_9, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_9, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_killed,
	cmd_skip(15 * Constants::FPS, 13),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_10, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_killed,
	cmd_skip(18 * Constants::FPS, 13),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_11, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_killed,
	cmd_newWave,
	//
	// Wave 2
	//
	// The first row of boxes is at y = -22 * Constants::FPS / INV_CAMERA_SPEED
	//
	cmd_newCameraPath(LUTs::CamTravelingId::CameraPath_c2_2),
#define CHAP2_BOXES_BASE (-22 * Constants::FPS / INV_CAMERA_SPEED)
#define BOX_SIZE 40
#define CHAP2_ROW(n) (CHAP2_BOXES_BASE - BOX_SIZE * (n))
#define CHAP2_COL(n) (160 + BOX_SIZE * (n - 2))
	// Static
	enemy(CHAP2_COL(0), CHAP2_ROW(0), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(0), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(0), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(0), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(0), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	// Boxes moving to the right
	// This is done by making a prop a box spawner
	enemy(CHAP2_COL(-1), CHAP2_ROW(1), 1, LUTs::BaseImageId::NONE, LUTs::EnemyPatternId::Pattern_2_12, Constants::LIGHT, 0, 0, TYPE_PROP),
	// Static
	enemy(CHAP2_COL(0), CHAP2_ROW(2), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(2), 20, LUTs::BaseImageId::BOX_SHADOW_1, LUTs::EnemyPatternId::Pattern_box, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(2), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(2), 20, LUTs::BaseImageId::BOX_SHADOW_1, LUTs::EnemyPatternId::Pattern_box, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(2), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	// Boxes moving to the left
	enemy(CHAP2_COL(5), CHAP2_ROW(3), 1, LUTs::BaseImageId::NONE, LUTs::EnemyPatternId::Pattern_2_13, Constants::LIGHT, 0, 0, TYPE_PROP),
	// Static
	enemy(CHAP2_COL(0), CHAP2_ROW(4), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(4), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(4), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(4), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(4), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	// Static, firing
	enemy(CHAP2_COL(0), CHAP2_ROW(6), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(6), 20, LUTs::BaseImageId::BOX_SHADOW_1, LUTs::EnemyPatternId::Pattern_2_14, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(6), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(6), 20, LUTs::BaseImageId::BOX_SHADOW_1, LUTs::EnemyPatternId::Pattern_2_14, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(6), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_PROP),
	// Static, firing
	enemy(CHAP2_COL(0), CHAP2_ROW(8), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(8), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_2_14, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(8), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_2_14, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(8), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_2_14, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(8), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	// Big wall opening when its on-screen Y coordinate is 100
	enemy(110, CHAP2_ROW(9), 1, LUTs::BaseImageId::PROP_WALL_LEFT, LUTs::EnemyPatternId::Pattern_2_wall, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(210, CHAP2_ROW(9), 1, LUTs::BaseImageId::PROP_WALL_RIGHT, LUTs::EnemyPatternId::Pattern_2_wall, Constants::LIGHT, 0, 0, TYPE_PROP),
	// Static
	enemy(CHAP2_COL(0), CHAP2_ROW(10), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(10), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(10), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(10), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	// 6 rows of 2 shooting solid boxes
	enemy(CHAP2_COL(1), CHAP2_ROW(11), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(11), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::SHADOW, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(13), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::SHADOW, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(13), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(15), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(15), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::SHADOW, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(17), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::SHADOW, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(17), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(19), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(19), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::SHADOW, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(1), CHAP2_ROW(21), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::SHADOW, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(3), CHAP2_ROW(21), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_15, Constants::LIGHT, 0, 0, TYPE_PROP),
	// Wait until the player gets to the beginning of the boxes column
	cmd_waitCamera(0, CHAP2_ROW(8)),
	cmd_newWave,
	// Boxes spawn from the last row
	enemy(CHAP2_COL(2), CHAP2_ROW(22), 1, LUTs::BaseImageId::NONE, LUTs::EnemyPatternId::Pattern_2_16, Constants::LIGHT, 0, 0, TYPE_PROP),
	// Subwave 1
	cmd_waitCamera(0, CHAP2_ROW(14)),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	// Subwave 2
	cmd_waitCamera(0, CHAP2_ROW(16)),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	// Subwave 3
	cmd_waitCamera(0, CHAP2_ROW(18)),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	// Subwave 4
	cmd_waitCamera(0, CHAP2_ROW(20)),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_17, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_wait(BOX_SIZE),
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_17, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	// Subwave 5
	enemy(CHAP2_COL(0), CHAP2_ROW(22), 50, LUTs::BaseImageId::ENEMY_GENERATOR_SHADOW, LUTs::EnemyPatternId::Pattern_2_18, Constants::SHADOW, 1, 10, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(22), 50, LUTs::BaseImageId::ENEMY_GENERATOR_LIGHT, LUTs::EnemyPatternId::Pattern_2_19, Constants::LIGHT, 0, 10, TYPE_BREAKABLE_PROP),
	// Big wall opening when its on-screen Y coordinate is 100
	enemy(110, CHAP2_ROW(23), 1, LUTs::BaseImageId::PROP_WALL_LEFT, LUTs::EnemyPatternId::Pattern_2_wall, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(210, CHAP2_ROW(23), 1, LUTs::BaseImageId::PROP_WALL_RIGHT, LUTs::EnemyPatternId::Pattern_2_wall, Constants::LIGHT, 0, 0, TYPE_PROP),
	// Wave 3
	//
	// 4 spaced rows of rotating shooting boxes
	enemy(CHAP2_COL(0), CHAP2_ROW(27), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_21, Constants::LIGHT, 1, 0, TYPE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(27), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_21, Constants::LIGHT, 1, 0, TYPE_PROP),
	enemy(CHAP2_COL(0), CHAP2_ROW(31), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_21, Constants::LIGHT, 1, 0, TYPE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(31), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_21, Constants::LIGHT, 1, 0, TYPE_PROP),
	enemy(CHAP2_COL(0), CHAP2_ROW(35), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_21, Constants::LIGHT, 1, 0, TYPE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(35), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_21, Constants::LIGHT, 1, 0, TYPE_PROP),
	enemy(CHAP2_COL(0), CHAP2_ROW(39), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_21, Constants::LIGHT, 1, 0, TYPE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(39), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_21, Constants::LIGHT, 1, 0, TYPE_PROP),
	// Subwave 1
	cmd_waitCamera(0, CHAP2_ROW(25)),
	cmd_newWave,
	enemy(CHAP2_COL(0), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) - 15, -10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0), -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4), 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) + 15, -10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4), -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	// Subwave 2
	cmd_waitCamera(0, CHAP2_ROW(27)),
	enemy(160, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_23, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_23, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_23, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_23, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_23, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_23, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	// Subwave 3
	cmd_waitCamera(0, CHAP2_ROW(29)),
	enemy(320, 30, 100, LUTs::BaseImageId::ENEMY_SHIP_3_LIGHT, LUTs::EnemyPatternId::Pattern_2_24, Constants::LIGHT, 0, 20, TYPE_ENEMY),
	// Subwave 4
	cmd_waitCamera(0, CHAP2_ROW(32)),
	enemy(CHAP2_COL(0) - 10, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) - 10, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) - 10, -40, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -50, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) + 10, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -10, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) + 10, -20, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) + 10, -40, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -50, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	// Subwave 5
	cmd_waitCamera(0, CHAP2_ROW(35)),
	enemy(0, 20, 30, LUTs::BaseImageId::ENEMY_SHIP_6_SHADOW, LUTs::EnemyPatternId::Pattern_2_25, Constants::SHADOW, 0, 20, TYPE_ENEMY),
	enemy(320, 20, 30, LUTs::BaseImageId::ENEMY_SHIP_6_SHADOW, LUTs::EnemyPatternId::Pattern_2_25, Constants::SHADOW, 0, 20, TYPE_ENEMY),
	// Subwave 6
	cmd_waitCamera(0, CHAP2_ROW(40)),
	enemy(0, 30, 100, LUTs::BaseImageId::ENEMY_SHIP_3_SHADOW, LUTs::EnemyPatternId::Pattern_2_26, Constants::SHADOW, 0, 20, TYPE_ENEMY),
	//
	// Wave 4
	//
	// 9 rows of centered boxes plus 4 rotating boxes
	enemy(CHAP2_COL(2), CHAP2_ROW(45), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(46), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(47), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(47) + 30, 20, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_29, Constants::SHADOW, 1, 5, TYPE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(48), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_2_27, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(49), 20, LUTs::BaseImageId::BOX_SHADOW_1, LUTs::EnemyPatternId::Pattern_box, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0), CHAP2_ROW(49) + 20, 20, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_29, Constants::LIGHT, 1, 5, TYPE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(50), 20, LUTs::BaseImageId::BOX_SHADOW_1, LUTs::EnemyPatternId::Pattern_box, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(51), 20, LUTs::BaseImageId::BOX_SHADOW_1, LUTs::EnemyPatternId::Pattern_2_28, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(51) + 10, 20, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_29, Constants::SHADOW, 1, 5, TYPE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(52), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(53), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0), CHAP2_ROW(53), 20, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_2_29, Constants::LIGHT, 1, 5, TYPE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(54), 20, LUTs::BaseImageId::BOX_LIGHT_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2), CHAP2_ROW(55), 1, LUTs::BaseImageId::BOX_SOLID_1, LUTs::EnemyPatternId::Pattern_box, Constants::LIGHT, 0, 0, TYPE_PROP),
	// Subwave 1
	cmd_waitCamera(0, CHAP2_ROW(46) + 10),
	enemy(CHAP2_COL(0) - 10, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -15, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) - 10, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -45, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) - 10, -60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -75, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	// Subwave 2
	cmd_waitCamera(0, CHAP2_ROW(48)),
	enemy(CHAP2_COL(4) + 10, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -15, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) + 10, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -45, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) + 10, -60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -75, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	// Subwave 3
	cmd_waitCamera(0, CHAP2_ROW(50)),
	enemy(CHAP2_COL(0) - 10, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -15, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) - 10, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -45, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) - 10, -60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(0) + 10, -75, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_22, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	// Subwave 4
	cmd_waitCamera(0, CHAP2_ROW(52)),
	enemy(CHAP2_COL(4) + 10, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -15, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) + 10, -30, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -45, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) + 10, -60, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(CHAP2_COL(4) - 10, -75, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_22, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	// Subwave 5
	//
	enemy(CHAP2_COL(0) - 20 + 13, CHAP2_ROW(55) - 12, 10, LUTs::BaseImageId::ENEMY_WALL_SHADOW, LUTs::EnemyPatternId::Pattern_prop, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0) - 20 + 26 + 13, CHAP2_ROW(55) - 12, 10, LUTs::BaseImageId::ENEMY_WALL_SHADOW, LUTs::EnemyPatternId::Pattern_prop, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0) - 20 + 52 + 13, CHAP2_ROW(55) - 12, 10, LUTs::BaseImageId::ENEMY_WALL_SHADOW, LUTs::EnemyPatternId::Pattern_prop, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0) - 20 + 13, CHAP2_ROW(55) + 12, 10, LUTs::BaseImageId::ENEMY_WALL_SHADOW, LUTs::EnemyPatternId::Pattern_prop, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0) - 20 + 26 + 13, CHAP2_ROW(55) + 12, 10, LUTs::BaseImageId::ENEMY_WALL_SHADOW, LUTs::EnemyPatternId::Pattern_prop, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0) - 20 + 52 + 13, CHAP2_ROW(55) + 12, 10, LUTs::BaseImageId::ENEMY_WALL_SHADOW, LUTs::EnemyPatternId::Pattern_prop, Constants::SHADOW, 0, 5, TYPE_BREAKABLE_PROP),

	enemy(CHAP2_COL(2) + 20 + 13, CHAP2_ROW(55) - 12, 10, LUTs::BaseImageId::ENEMY_WALL_LIGHT, LUTs::EnemyPatternId::Pattern_prop, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2) + 20 + 26 + 13, CHAP2_ROW(55) - 12, 10, LUTs::BaseImageId::ENEMY_WALL_LIGHT, LUTs::EnemyPatternId::Pattern_prop, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2) + 20 + 52 + 13, CHAP2_ROW(55) - 12, 10, LUTs::BaseImageId::ENEMY_WALL_LIGHT, LUTs::EnemyPatternId::Pattern_prop, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2) + 20 + 13, CHAP2_ROW(55) + 12, 10, LUTs::BaseImageId::ENEMY_WALL_LIGHT, LUTs::EnemyPatternId::Pattern_prop, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2) + 20 + 26 + 13, CHAP2_ROW(55) + 12, 10, LUTs::BaseImageId::ENEMY_WALL_LIGHT, LUTs::EnemyPatternId::Pattern_prop, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(2) + 20 + 52 + 13, CHAP2_ROW(55) + 12, 10, LUTs::BaseImageId::ENEMY_WALL_LIGHT, LUTs::EnemyPatternId::Pattern_prop, Constants::LIGHT, 0, 5, TYPE_BREAKABLE_PROP),
	//
	enemy(CHAP2_COL(0), CHAP2_ROW(57), 30, LUTs::BaseImageId::ENEMY_GENERATOR_LIGHT, LUTs::EnemyPatternId::Pattern_2_30, Constants::LIGHT, 1, 10, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0), CHAP2_ROW(58), 30, LUTs::BaseImageId::ENEMY_GENERATOR_LIGHT, LUTs::EnemyPatternId::Pattern_2_30, Constants::LIGHT, 1, 10, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(0), CHAP2_ROW(59), 30, LUTs::BaseImageId::ENEMY_GENERATOR_LIGHT, LUTs::EnemyPatternId::Pattern_2_30, Constants::LIGHT, 1, 10, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(57), 30, LUTs::BaseImageId::ENEMY_GENERATOR_SHADOW, LUTs::EnemyPatternId::Pattern_2_31, Constants::SHADOW, 1, 10, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(58), 30, LUTs::BaseImageId::ENEMY_GENERATOR_SHADOW, LUTs::EnemyPatternId::Pattern_2_31, Constants::SHADOW, 1, 10, TYPE_BREAKABLE_PROP),
	enemy(CHAP2_COL(4), CHAP2_ROW(59), 30, LUTs::BaseImageId::ENEMY_GENERATOR_SHADOW, LUTs::EnemyPatternId::Pattern_2_31, Constants::SHADOW, 1, 10, TYPE_BREAKABLE_PROP),

	// Big walls forming a opening that's a demi-box wide (20 px)
	enemy(100, CHAP2_ROW(60), 1, LUTs::BaseImageId::PROP_WALL_LEFT, LUTs::EnemyPatternId::Pattern_prop, Constants::LIGHT, 0, 0, TYPE_PROP),
	enemy(220, CHAP2_ROW(60), 1, LUTs::BaseImageId::PROP_WALL_RIGHT, LUTs::EnemyPatternId::Pattern_prop, Constants::LIGHT, 0, 0, TYPE_PROP),
	//
	// Wave 5
	//
	cmd_waitCamera(0, CHAP2_ROW(61)),
	cmd_newWave,
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_34, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(160, -100, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_34, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	cmd_killed,
	//
	// Wave 6
	//
	cmd_newWave,
	enemy(0, 30, 100, LUTs::BaseImageId::ENEMY_SHIP_3_SHADOW, LUTs::EnemyPatternId::Pattern_2_35, Constants::SHADOW, 1, 20, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_36, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_SHADOW, LUTs::EnemyPatternId::Pattern_2_36, Constants::SHADOW, 1, 4, TYPE_ENEMY),
	enemy(320, 30, 100, LUTs::BaseImageId::ENEMY_SHIP_3_LIGHT, LUTs::EnemyPatternId::Pattern_2_35, Constants::LIGHT, 1, 20, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_36, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	enemy(0, 0, 1, LUTs::BaseImageId::ENEMY_SHIP_0_LIGHT, LUTs::EnemyPatternId::Pattern_2_36, Constants::LIGHT, 1, 4, TYPE_ENEMY),
	cmd_joint(1, 0, 0, 0, 0),
	cmd_joint(2, 0, 0, 0, 0),
	cmd_joint(4, 3, 0, 0, 0),
	cmd_joint(5, 3, 0, 0, 0),
	cmd_killed,
	cmd_wait(64),
	cmd_newCameraPath(LUTs::CamTravelingId::CameraPath_c2_boss),
	cmd_fightBoss(1),
	LVLSTR_CHAPTEREND,
	LVLSTR_END
};
